config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :places, except: [:destroy]

  root 'places#index'

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id          :integer          not null, primary key
#  title       :string
#  address     :string
#  city        :string
#  country     :string
#  county      :string
#  postal_code :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  latitude    :float
#  longitude   :float
#

class Location < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed?}
  
  def geocoded_by
    "#{address}, #{city}, #{country}, #{county}, #{postal_code}"
  end



end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  address     :string
#  latitude    :float
#  longitude   :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Place < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:title, :address, :city, :country, :county, :postal_code)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.order('created_at DESC')
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = 'New place added'
      redirect_to action: 'show', id: @place.id
    else
      render 'new'
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update_attributes(place_params)
      flash[:success] = 'Place updated'
      redirect_to action: 'show', id: @place.id
    else
      render 'edit'
    end
  end

  private

  def place_params
    params.require(:place).permit(:title, :description, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    meta name='viewport' content='width=device-width, initial-scale=1'
    meta name='keywords' content='template language'
    meta name='author' content='Josef Zacek'
    title Rails Records Sorting
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
      
  body
    nav.navbar.navbar-inverse
      .container
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Geocoder', root_path, class: 'navbar-brand'

        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav
            li = link_to 'Places', places_path
            li = link_to 'Locations', locations_path


    .container
      - flash.each do |key, value|
        div class="alert alert-#{key} fade in"
          button.close data-dismiss='alert'
            | &times; 
          p = value
      
      = yield
      hr
      footer
        p Created by #{link_to 'josefzacek.com', 'http://josefzacek.com'}

    script src="https://maps.googleapis.com/maps/api/js?v=3.exp&callback=initialize"

app/views/locations/_form.html.slim
= form_for(@location) do |f|
  - if @location.errors.any?
    #error_explanation
      h2 = "#{pluralize(@location.errors.count, 'error')} prohibited this location from being saved"

      ul
        - @location.errors.full_messages.each do |message|
          li = message

  = form_for @location do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :address
      = f.text_field :address, class: 'form-control'
    .form-group
      = f.label :city
      = f.text_field :city, class: 'form-control'
    .form-group
      = f.label :country
      = f.text_field :country, class: 'form-control'
    .form-group
      = f.label :county
      = f.text_field :county, class: 'form-control'
    .form-group
      = f.label :postal_code
      = f.text_field :postal_code, class: 'form-control'
    p = f.submit class: 'btn btn-default'

app/views/locations/edit.html.slim
.row
  .col-md-6.col-md-offset-3
    h1.text-center Edit location

    = render 'form'

    p = link_to('Show', @location, class: 'btn btn-default')

    p  = link_to('Back', locations_path, class: 'btn btn-default')

app/views/locations/index.html.slim
h1 Listing Locations

p = link_to 'Add new location', new_location_path, class: 'btn btn-default'

ul.list-group
  - @locations.each do |location|
    li.list-group-item
      = link_to(location.title, location_path(location))
      '  /
      = link_to('Edit', edit_location_path(location), class: 'text-warning')
      '  /
      = link_to 'Destroy', location, class: 'text-danger',  method: :delete, data: { confirm: 'Are you sure?' }

app/views/locations/new.html.slim
.row
  .col-md-6.col-md-offset-3
    h1.text-center Add location

    = render 'form'

    p  = link_to('Back', locations_path, class: 'btn btn-default')

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @location.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @location.country %>
</p>

<p>
  <strong>County:</strong>
  <%= @location.county %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @location.postal_code %>
</p>


<p>Map:</p>


<%= content_tag "div", id: "map_canvas", data: { longitude: @location.longitude, latitude: @location.latitude } do %>
    <% end %>



<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/places/edit.html.slim
.row
  .col-md-6.col-md-offset-3
    h1 Update place
    = form_for @place do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'
      .form-group
        = f.label :address
        = f.text_field :address, class: 'form-control'
      p
        = f.submit 'Update place', class: 'btn btn-default'
    p = link_to 'Back', root_path

app/views/places/index.html.slim
h2 Listing of places

p = link_to 'Add new place', new_place_path, class: 'btn btn-default'

ul.list-group
  - @places.each do |place| 
      li.list-group-item
        = link_to(place.title, place_path(place))

app/views/places/new.html.slim
.row
  .col-md-6.col-md-offset-3
    h1 Add new place
    = form_for @place do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'
      .form-group
        = f.label :address
        = f.text_field :address, class: 'form-control'
      p
        = f.submit 'Create place', class: 'btn btn-default'
    p = link_to 'Back', root_path

app/views/places/show.html.slim
h1 Place details
.row
  .col-md-6
    p
      b Title:
    p = @place.title
    
    p
      b Description: 
    p = @place.description

    p
      b Address: 
    p = @place.address

    .btn-group    
      p = link_to 'Home page', root_path, class: 'btn btn-default'

      p = link_to 'Edit', edit_place_path, class: 'btn btn-default'

  .col-md-6

    p
      b Map:

    = content_tag :div, id: "map_canvas", data: {title: @place.title, latitude: @place.latitude, longitude: @place.longitude} do